name: "Common airport Checkin"

on:
  schedule:
    - cron: "0 14 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.16

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 设置代理环境变量
      - name: Set up proxy from secrets
        run: |
          echo "Setting up proxy from GitHub Secrets..."
        env:
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}  # 从 Secrets 传递 HTTP 代理
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}  # 从 Secrets 传递 HTTPS 代理

      - name: Run sign
        env:
          URL: ${{ secrets.URL }}
          SCKEY: ${{ secrets.SCKEY }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          CONFIG: ${{ secrets.CONFIG }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}  # 再次传递代理环境变量
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}  # 再次传递代理环境变量
        run: |
          python3 ./main.py
